name: .NETbuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    
    - name: run
      run: dotnet run -p generator/src/generator.csproj -- . "https://evartuna.github.io/real/" _site
    - name: copy
      run: ./copy-assets.bash _site
    
    - name: config
      run: | 
          git config --global user.email "kwang1406@gmail.com" 
          git config --global user.name "evartuna"
           
    - name: git
      run: |
          rm .gitignore  
          git add _site  
          git commit -m "build"
          git push origin `git subtree split --prefix _site main`:gh-pages --force

